repoowner="joomla"
repository="https://github.com//$repoowner/joomla-cms.git"
#repository="https://github.com//MacJoom/joomla-cms.git"
joomladir="joomla-cms"
majversion="4"
minversion="4"
patchversion="6"
oldmajversion="4"
oldminversion="4"
oldpatchversion="5"
oldextra="rc"
oldextranum="1"
extra=""
extranum=""
extranext=""
extranumnext=""
codename="Pamoja"
reldate="2024-07-09 16:00"
revdate="2024-07-09 16:01"
checkout="$majversion.$minversion-dev"
infourl="https:\/\/www.joomla.org\/announcements\/release-news\/5909-joomla-5-1-2-and-joomla-4-4-6-are-here.html"
#infourl="https:\/\/www.joomla.org\/announcements\/release-news\/5907-joomla-5-1-0-and-joomla-4-4-4-are-here.html"
if [ -z "$extra" ]
then
    branch="$majversion.$minversion.$patchversion-stable"
    tag="$majversion.$minversion.$patchversion"
    commit="Joomla! $majversion.$minversion.$patchversion Stable"
    nextpatchversion=$((patchversion+1))
    next="$majversion.$minversion.$nextpatchversion"
else
    branch="$majversion.$minversion.$patchversion-$extra"
    tag="$majversion.$minversion.$patchversion-$extra$extranum"
    commit="Joomla! $majversion.$minversion.$patchversion ${extra^} $extranum"
    next="$majversion.$minversion.$patchversion-$extranext$extranumnext"
fi

echo "Repository: $repository"
echo "Checkout: $checkout"
echo "Branch: $branch"
echo "Tag: $tag"
echo "Commit: $commit"
echo "Next: $next"
echo "Release Date: $reldate"
echo "Revert to Dev Date: $revdate"
echo "Infourl: $infourl"